import { ReactNode } from "react";
import "@src/styles/globals.css";
import { MovieProvider } from "@src/contexts/movieContext";
import Head from "next/head";
import Nav from "@src/components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
        />
      </head>

      <body className="bg-black">
        <MovieProvider>
          <Nav />
          <div className="mt-16">{children}</div>
        </MovieProvider>
      </body>
    </html>
  );
}
